all:
	cc -std=c++11 -I../../src/ -I/usr/include/SDL2 -lstdc++ -lSDL2 -Wall -Wextra -Wshadow -O0 *.cpp ../../src/surface.cpp ../../src/gm1.cpp ../../src/tgx.cpp ../../src/rw.cpp ../../src/geometry.cpp ../../src/atlas.cpp -o a.out -g
